### ISSUE TITLE
How to get window list

### ISSUE THREAD

**Issue by snnsnn** [HeinrichAD/libxdo#2]
Hi Heinrich,

I was trying to search windows by name to get a specific window but could not get it working. Please can you help me. Here is the function I am trying to use:

```javascript
'xdo_search_windows' : [ 'int', [ 
      p_struct_xdo_t,                   // const xdo_t *xdo
      p_struct_xdo_search_t,            // const xdo_search_t *search
      ref.refType(ref.refType('int')),  // Window **windowlist_ret
      ref.refType('int'),               // unsigned int *nwindows_ret
  ] ],
```

The library does not expose any `windowlist_ret`. Do I have to get it mysef from the source module? I don't understand FFI but was hoping to work something out. Thank you.

**Comment by HeinrichAD** [comment]
Hi SnnSnn,

unfortunately, I never used `xdo_search_windows`. To be fair I only used the simplest methods.

To answer your question: `windowlist_ret` and `nwindows_ret` just need to be `int`.
But the library should provide e.g. types like `xdo_search_t`, which can then be used as follows:
```node
let search = new struct_xdo_search_t();
search.title = "Signal";
xdo_search_windows(xdo, search.ref(), ...);
```

As far as I can tell, this library is incomplete.
But since I don't use most of the methods and unfortunately don't have time for this project anymore.

**If someone wants to take over the project, I'm happy to give them the appropriate permissions to the repository.**

**Comment by snnsnn** [comment]
@HeinrichAD Ok. I will look into alternatives. Thank you.
